package server
import "net/http"
func(s *Server)dashboard(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(dashHTML))}
const dashHTML=`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Presskit</title>
<style>:root{--bg:#1a1410;--bg2:#241e18;--bg3:#2e261e;--rust:#c45d2c;--rl:#e8753a;--leather:#a0845c;--cream:#f0e6d3;--cd:#bfb5a3;--cm:#7a7060;--gold:#d4a843;--green:#4a9e5c;--mono:'JetBrains Mono',Consolas,monospace;--serif:'Libre Baskerville',Georgia,serif}*{margin:0;padding:0;box-sizing:border-box}body{background:var(--bg);color:var(--cream);font-family:var(--mono);font-size:13px;line-height:1.6}.hdr{padding:.6rem 1.2rem;border-bottom:1px solid var(--bg3);display:flex;justify-content:space-between;align-items:center}.hdr h1{font-family:var(--serif);font-size:1rem}.hdr h1 span{color:var(--rl)}.main{max-width:700px;margin:0 auto;padding:1rem}.btn{font-family:var(--mono);font-size:.68rem;padding:.3rem .6rem;border:1px solid;cursor:pointer;background:transparent}.btn-p{border-color:var(--rust);color:var(--rl)}.btn-p:hover{background:var(--rust);color:var(--cream)}.section{margin-bottom:1.5rem}.section-title{font-size:.65rem;text-transform:uppercase;letter-spacing:2px;color:var(--rust);margin-bottom:.5rem;display:flex;justify-content:space-between;align-items:center}.item{background:var(--bg2);border:1px solid var(--bg3);padding:.5rem .7rem;margin-bottom:.3rem;display:flex;align-items:center;gap:.5rem;font-size:.75rem}.item-name{font-weight:600;flex:1}.item-meta{font-size:.65rem;color:var(--cm)}.empty{text-align:center;padding:1rem;color:var(--cm);font-style:italic;font-family:var(--serif);font-size:.78rem}.modal-bg{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.65);display:flex;align-items:center;justify-content:center;z-index:100}.modal{background:var(--bg2);border:1px solid var(--bg3);padding:1.5rem;width:90%;max-width:450px}.modal h2{font-family:var(--serif);font-size:.9rem;margin-bottom:1rem}label.fl{display:block;font-size:.65rem;color:var(--leather);text-transform:uppercase;letter-spacing:1px;margin-bottom:.2rem;margin-top:.5rem}input[type=text],textarea{background:var(--bg);border:1px solid var(--bg3);color:var(--cream);padding:.35rem .5rem;font-family:var(--mono);font-size:.78rem;width:100%;outline:none}textarea{resize:vertical;min-height:60px}</style>
<link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital@0;1&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
</head><body><div class="hdr"><h1><span>Presskit</span></h1><span style="font-size:.65rem;color:var(--cm)">Public: <a href="/api/kit" style="color:var(--rl)">/api/kit</a></span></div>
<div class="main" id="content"></div><div id="modal"></div>
<script>
async function api(u,o){return(await fetch(u,o)).json()}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
async function load(){
const[ad,fd,cd]=await Promise.all([api('/api/assets'),api('/api/facts'),api('/api/contacts')]);
const assets=(ad.assets||[]).map(a=>'<div class="item"><span class="item-name">'+esc(a.name)+'</span>'+(a.category?'<span style="font-size:.6rem;padding:0 .25rem;background:var(--bg3);color:var(--ll);border-radius:2px">'+esc(a.category)+'</span>':'')+(a.url?'<a href="'+esc(a.url)+'" target="_blank" style="font-size:.6rem">link</a>':'')+
'<span style="cursor:pointer;font-size:.55rem;color:var(--cm)" onclick="delA(\''+a.id+'\')">del</span></div>').join('');
const facts=(fd.facts||[]).map(f=>'<div class="item"><span style="color:var(--leather)">'+esc(f.label)+':</span> <span>'+esc(f.value)+'</span><span style="cursor:pointer;font-size:.55rem;color:var(--cm);margin-left:auto" onclick="delF(\''+f.id+'\')">del</span></div>').join('');
const contacts=(cd.contacts||[]).map(c=>'<div class="item"><span class="item-name">'+esc(c.name)+'</span><span class="item-meta">'+esc(c.role)+'</span>'+(c.email?'<span class="item-meta">'+esc(c.email)+'</span>':'')+
'<span style="cursor:pointer;font-size:.55rem;color:var(--cm)" onclick="delC(\''+c.id+'\')">del</span></div>').join('');
document.getElementById('content').innerHTML=
'<div class="section"><div class="section-title">Brand Assets <button class="btn btn-p" style="font-size:.55rem;padding:.1rem .3rem" onclick="addAsset()">+</button></div>'+(assets||'<div class="empty">No assets yet.</div>')+'</div>'+
'<div class="section"><div class="section-title">Company Facts <button class="btn btn-p" style="font-size:.55rem;padding:.1rem .3rem" onclick="addFact()">+</button></div>'+(facts||'<div class="empty">No facts yet.</div>')+'</div>'+
'<div class="section"><div class="section-title">Press Contacts <button class="btn btn-p" style="font-size:.55rem;padding:.1rem .3rem" onclick="addContact()">+</button></div>'+(contacts||'<div class="empty">No contacts yet.</div>')+'</div>'}
function addAsset(){document.getElementById('modal').innerHTML='<div class="modal-bg" onclick="if(event.target===this)closeModal()"><div class="modal"><h2>Add Asset</h2><label class="fl">Name</label><input type="text" id="a-name"><label class="fl">Category</label><input type="text" id="a-cat" placeholder="logo, screenshot, icon"><label class="fl">URL</label><input type="text" id="a-url" placeholder="https://..."><label class="fl">Description</label><input type="text" id="a-desc"><div style="display:flex;gap:.5rem;margin-top:1rem"><button class="btn btn-p" onclick="saveA()">Add</button><button class="btn" style="border-color:var(--bg3);color:var(--cm)" onclick="closeModal()">Cancel</button></div></div></div>'}
async function saveA(){const b={name:document.getElementById('a-name').value,category:document.getElementById('a-cat').value,url:document.getElementById('a-url').value,description:document.getElementById('a-desc').value};if(!b.name){alert('Name required');return};await api('/api/assets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});closeModal();load()}
function addFact(){document.getElementById('modal').innerHTML='<div class="modal-bg" onclick="if(event.target===this)closeModal()"><div class="modal"><h2>Add Fact</h2><label class="fl">Label</label><input type="text" id="f-label" placeholder="Founded"><label class="fl">Value</label><input type="text" id="f-value" placeholder="2024"><div style="display:flex;gap:.5rem;margin-top:1rem"><button class="btn btn-p" onclick="saveF()">Add</button><button class="btn" style="border-color:var(--bg3);color:var(--cm)" onclick="closeModal()">Cancel</button></div></div></div>'}
async function saveF(){const b={label:document.getElementById('f-label').value,value:document.getElementById('f-value').value};if(!b.label){alert('Label required');return};await api('/api/facts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});closeModal();load()}
function addContact(){document.getElementById('modal').innerHTML='<div class="modal-bg" onclick="if(event.target===this)closeModal()"><div class="modal"><h2>Add Contact</h2><label class="fl">Name</label><input type="text" id="c-name"><label class="fl">Role</label><input type="text" id="c-role"><label class="fl">Email</label><input type="text" id="c-email"><label class="fl">Bio</label><textarea id="c-bio" rows="2"></textarea><div style="display:flex;gap:.5rem;margin-top:1rem"><button class="btn btn-p" onclick="saveC()">Add</button><button class="btn" style="border-color:var(--bg3);color:var(--cm)" onclick="closeModal()">Cancel</button></div></div></div>'}
async function saveC(){const b={name:document.getElementById('c-name').value,role:document.getElementById('c-role').value,email:document.getElementById('c-email').value,bio:document.getElementById('c-bio').value};if(!b.name){alert('Name required');return};await api('/api/contacts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});closeModal();load()}
async function delA(id){await api('/api/assets/'+id,{method:'DELETE'});load()}
async function delF(id){await api('/api/facts/'+id,{method:'DELETE'});load()}
async function delC(id){await api('/api/contacts/'+id,{method:'DELETE'});load()}
function closeModal(){document.getElementById('modal').innerHTML=''}
load()
</script></body></html>`
